[package]
name = "fsm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-process = "2.4.0"
bytesize = "2.0.1"
chrono = { version = "0.4.41", features = ["serde"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
directories = "6.0.0"
futures = "0.3.31"
humantime-serde = "1.1.1"
ignore = "0.4.23"
moka = { version = "0.12.10", features = ["future"] }
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full", "macros", "rt-multi-thread", "time"] }
toml = "0.9.2"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "env-filter", "json", "serde", "serde_json"] }
walkdir = "2.5.0"
